# Change these first
owner: opensourcepos # Your GitHub username
repo: opensourcepos # Your GitHub repository name

# Add your sites here
sites:
  - name: Demo
    url: https://demo.opensourcepos.org
  - name: Dev
    url: https://dev.opensourcepos.org
  - name: Weblate
    url: https://translate.opensourcepos.org
 

status-website:

  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Deployment page uptime monitor"
  introMessage: This page shows **real-time** deploy stats for our test and dev servers.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
